corpid: "ww89219670ad1e9a4e"
corpsecret: "4flRSUlS1HteEQ9yQaqcKHmN3_Q10TSkPn7E5sJh0YM"
contactSecret: "_YyJN7ys2GW58pQ8Z9ML4OBeBAO6PSxaqX6bJK2aHtI"
current: test
env:
  dev:
    "qyapi.weixin.qq.com": "qyapi.weixin.qq.com"
  test:
    "qyapi.weixin.qq.com": "183.3.224.149"